from datetime import datetime
from click import command
import discord
intents = discord.Intents.default()   #網關預設值
intents.typing = False
intents.presences = False
intents.members = True
from discord.ext import commands
from core.classes import Cog_Extension
import datetime
from datetime import datetime,timezone,timedelta
import json,random

with open('setting.json', 'r', encoding='utf8') as jfile:
    jdata = json.load(jfile)

class Gamming(Cog_Extension):

    @commands.command()
    async def set_pic(self, ctx , url:str):
        with open('setting.json', 'r', encoding='utf8') as jfile:
            jdata = json.load(jfile)
        jdata['url_pic_1'].append(url)
        with open('setting.json', 'w', encoding='utf8') as jfile:
            json.dump(jdata, jfile, indent=4)
        await ctx.send(f'success!')
        
    @commands.group()
    async def uma(self,ctx):
        pass

    @uma.command()
    async def 特別週(self, ctx):
        random_image_1_1 = random.choice(jdata['image_1_1'])
        embed=discord.Embed(title="特別週", url="https://zh.wikipedia.org/zh-tw/%E7%89%B9%E5%88%A5%E9%80%B1", description="小特、特別肥、スペシャルウィーク", color=0x00ffff, timestamp= datetime.utcnow())
        embed.set_author(name="賽馬娘Pretty Derby", url=jdata['uma_wiki_url'], icon_url="https://upload.wikimedia.org/wikipedia/zh/e/ed/Umamusume_logo.png")
        embed.set_thumbnail(url=jdata['image_1_1_0'])
        embed.set_image(url=random_image_1_1)
        embed.add_field(name="CV：", value="和氣杏未", inline=True)
        embed.add_field(name="身高：", value="158cm", inline=True)
        embed.add_field(name="體重：", value="微減（競賽前略顯緊張）", inline=True)
        embed.add_field(name="三圍：", value="B79/W57/H81", inline=True)
        embed.add_field(name="生日：", value="5月2日", inline=True)
        # embed.add_field(name="初始星數：", value="三星", inline=True)
        # embed.add_field(name="場地資質：", value="草地:A 沙地:G", inline=True)
        # embed.add_field(name="距離資質：", value="短距離:F 一哩:C 中距離:A 長距離:A", inline=True)
        # embed.add_field(name="腳質資質：", value="領頭:G 前列:A 居中:A 後追:C", inline=True)
        # embed.add_field(name="成長率：", value="持久力+20% 智力+10%", inline=True)
        await ctx.send(embed=embed)
    
    @uma.command()
    async def 無聲鈴鹿(self, ctx):
        random_image_1_2 = random.choice(jdata['image_1_2'])
        embed=discord.Embed(title="無聲鈴鹿", url="https://ja.wikipedia.org/wiki/%E3%82%B5%E3%82%A4%E3%83%AC%E3%83%B3%E3%82%B9%E3%82%B9%E3%82%BA%E3%82%AB", description="サイレンススズカ", color=0x00ffff, timestamp= datetime.utcnow())
        embed.set_author(name="賽馬娘Pretty Derby", url=jdata['uma_wiki_url'], icon_url=jdata['uma_logo'])
        embed.set_thumbnail(url=jdata['image_1_2_0'])
        embed.set_image(url=random_image_1_2)
        embed.add_field(name="CV：", value="高野麻里佳", inline=True)
        embed.add_field(name="身高：", value="161cm", inline=True)
        embed.add_field(name="體重：", value="無增減", inline=True)
        embed.add_field(name="三圍：", value="B70/W53/H79", inline=True)
        embed.add_field(name="生日：", value="5月1日", inline=True)

        await ctx.send(embed=embed)
    
    @uma.command()
    async def 東海帝皇(self, ctx):
        random_image_1_3 = random.choice(jdata['image_1_3'])
        embed=discord.Embed(title="東海帝皇", url="https://zh.wikipedia.org/zh-tw/%E6%9D%B1%E6%B5%B7%E5%B8%9D%E7%8E%8B", description="東海帝王、トウカイテイオー", color=0x00ffff, timestamp= datetime.utcnow())
        embed.set_author(name="賽馬娘Pretty Derby", url=jdata['uma_wiki_url'], icon_url="https://upload.wikimedia.org/wikipedia/zh/e/ed/Umamusume_logo.png")
        embed.set_thumbnail(url=jdata['image_1_3_0'])
        embed.set_image(url=random_image_1_3)
        embed.add_field(name="CV：", value="Machico", inline=True)
        embed.add_field(name="身高：", value="150cm", inline=True)
        embed.add_field(name="體重：", value="無增減", inline=True)
        embed.add_field(name="三圍：", value="B77/W54/H76", inline=True)
        embed.add_field(name="生日：", value="4月20日", inline=True)

        await ctx.send(embed=embed)
    
    @uma.command()
    async def 丸善斯基(self, ctx):
        random_image_1_4 = random.choice(jdata['image_1_4'])
        embed=discord.Embed(title="丸善斯基", url="https://ja.wikipedia.org/wiki/%E3%83%9E%E3%83%AB%E3%82%BC%E3%83%B3%E3%82%B9%E3%82%AD%E3%83%BC", description="阿姨、丸善阿姨、マルゼンスキー", color=0x00ffff, timestamp= datetime.utcnow())
        embed.set_author(name="賽馬娘Pretty Derby", url=jdata['uma_wiki_url'], icon_url="https://upload.wikimedia.org/wikipedia/zh/e/ed/Umamusume_logo.png")
        embed.set_thumbnail(url=jdata['image_1_4_0'])
        embed.set_image(url=random_image_1_4)
        embed.add_field(name="CV：", value="Lynn", inline=True)
        embed.add_field(name="身高：", value="164cm", inline=True)
        embed.add_field(name="體重：", value="調整狀態相當理想", inline=True)
        embed.add_field(name="三圍：", value="B92/W58/H88", inline=True)
        embed.add_field(name="生日：", value="5月19日", inline=True)

        await ctx.send(embed=embed)
    
    @uma.command()
    async def 富士奇石(self, ctx):
        random_image_1_5 = random.choice(jdata['image_1_5'])
        embed=discord.Embed(title="富士奇石", url="https://ja.wikipedia.org/wiki/%E3%83%95%E3%82%B8%E3%82%AD%E3%82%BB%E3%82%AD", description="富士奇蹟、フジキセキ", color=0x00ffff, timestamp= datetime.utcnow())
        embed.set_author(name="賽馬娘Pretty Derby", url=jdata['uma_wiki_url'], icon_url="https://upload.wikimedia.org/wikipedia/zh/e/ed/Umamusume_logo.png")
        embed.set_thumbnail(url=jdata['image_1_5_0'])
        embed.set_image(url=random_image_1_5)
        embed.add_field(name="CV：", value="松井惠理子", inline=True)
        embed.add_field(name="身高：", value="168cm", inline=True)
        embed.add_field(name="體重：", value="無增減", inline=True)
        embed.add_field(name="三圍：", value="B84/W58/H82", inline=True)
        embed.add_field(name="生日：", value="4月15日", inline=True)

        await ctx.send(embed=embed)
    
    @uma.command()
    async def 小栗帽(self, ctx):
        random_image_1_6 = random.choice(jdata['image_1_6'])
        embed=discord.Embed(title="小栗帽", url="https://zh.wikipedia.org/zh-tw/%E5%B0%8F%E6%A0%97%E5%B8%BD", description="オグリキャップ", color=0x00ffff, timestamp= datetime.utcnow())
        embed.set_author(name="賽馬娘Pretty Derby", url=jdata['uma_wiki_url'], icon_url="https://upload.wikimedia.org/wikipedia/zh/e/ed/Umamusume_logo.png")
        embed.set_thumbnail(url=jdata['image_1_6_0'])
        embed.set_image(url=random_image_1_6)
        embed.add_field(name="CV：", value="高柳知葉", inline=True)
        embed.add_field(name="身高：", value="167cm", inline=True)
        embed.add_field(name="體重：", value="微增（吃太多）", inline=True)
        embed.add_field(name="三圍：", value="B82/W57/H82", inline=True)
        embed.add_field(name="生日：", value="3月27日", inline=True)

        await ctx.send(embed=embed)
    
    @uma.command()
    async def 黃金船(self, ctx):
        random_image_2_1 = random.choice(jdata['image_2_1'])
        embed=discord.Embed(title="黃金船", url="https://ja.wikipedia.org/wiki/%E3%82%B4%E3%83%BC%E3%83%AB%E3%83%89%E3%82%B7%E3%83%83%E3%83%97", description="ゴールドシップ", color=0x00ffff, timestamp= datetime.utcnow())
        embed.set_author(name="賽馬娘Pretty Derby", url=jdata['uma_wiki_url'], icon_url="https://upload.wikimedia.org/wikipedia/zh/e/ed/Umamusume_logo.png")
        embed.set_thumbnail(url=jdata['image_2_1_0'])
        embed.set_image(url=random_image_2_1)
        embed.add_field(name="CV：", value="上田瞳", inline=True)
        embed.add_field(name="身高：", value="170cm", inline=True)
        embed.add_field(name="體重：", value="無法測定", inline=True)
        embed.add_field(name="三圍：", value="B88/W55/H88", inline=True)
        embed.add_field(name="生日：", value="3月6日", inline=True)
        await ctx.send(embed=embed)
    
    @uma.command()
    async def 伏特加(self, ctx):
        random_image_2_2 = random.choice(jdata['image_2_2'])
        embed=discord.Embed(title="伏特加", url="https://zh.wikipedia.org/zh-tw/%E4%BC%8F%E7%89%B9%E5%8A%A0_(%E9%A6%AC)", description="Vodka", color=0x00ffff, timestamp= datetime.utcnow())
        embed.set_author(name="賽馬娘Pretty Derby", url=jdata['uma_wiki_url'], icon_url="https://upload.wikimedia.org/wikipedia/zh/e/ed/Umamusume_logo.png")
        embed.set_thumbnail(url=jdata['image_2_2_0'])
        embed.set_image(url=random_image_2_2)
        embed.add_field(name="CV：", value="大橋彩香", inline=True)
        embed.add_field(name="身高：", value="165cm", inline=True)
        embed.add_field(name="體重：", value="無增減", inline=True)
        embed.add_field(name="三圍：", value="B76/W55/H78", inline=True)
        embed.add_field(name="生日：", value="4月4日", inline=True)

        await ctx.send(embed=embed)
    
    @uma.command()
    async def 大和赤驥(self, ctx):
        random_image_2_3 = random.choice(jdata['image_2_3'])
        embed=discord.Embed(title="大和赤驥", url="https://ja.wikipedia.org/wiki/%E3%83%80%E3%82%A4%E3%83%AF%E3%82%B9%E3%82%AB%E3%83%BC%E3%83%AC%E3%83%83%E3%83%88", description="ダイワスカーレット", color=0x00ffff, timestamp= datetime.utcnow())
        embed.set_author(name="賽馬娘Pretty Derby", url=jdata['uma_wiki_url'], icon_url="https://upload.wikimedia.org/wikipedia/zh/e/ed/Umamusume_logo.png")
        embed.set_thumbnail(url=jdata['image_2_3_0'])
        embed.set_image(url=random_image_2_3)
        embed.add_field(name="CV：", value="木村千咲", inline=True)
        embed.add_field(name="身高：", value="163cm", inline=True)
        embed.add_field(name="體重：", value="不明（拒絕測量）", inline=True)
        embed.add_field(name="三圍：", value="B90/W56/H82", inline=True)
        embed.add_field(name="生日：", value="5月13日", inline=True)

        await ctx.send(embed=embed)
    
    @uma.command()
    async def 大樹快車(self, ctx):
        random_image_2_4 = random.choice(jdata['image_2_4'])
        embed=discord.Embed(title="大樹快車", url="https://ja.wikipedia.org/wiki/%E3%82%BF%E3%82%A4%E3%82%AD%E3%82%B7%E3%83%A3%E3%83%88%E3%83%AB", description="タイキシャトル", color=0x00ffff, timestamp= datetime.utcnow())
        embed.set_author(name="賽馬娘Pretty Derby", url=jdata['uma_wiki_url'], icon_url="https://upload.wikimedia.org/wikipedia/zh/e/ed/Umamusume_logo.png")
        embed.set_thumbnail(url=jdata['image_2_4_0'])
        embed.set_image(url=random_image_2_4)
        embed.add_field(name="CV：", value="大坪由佳", inline=True)
        embed.add_field(name="身高：", value="172cm", inline=True)
        embed.add_field(name="體重：", value="微增（不過no problem!）", inline=True)
        embed.add_field(name="三圍：", value="B94/W59/H90", inline=True)
        embed.add_field(name="生日：", value="3月23日", inline=True)

        await ctx.send(embed=embed)
    
    @uma.command()
    async def 草上飛(self, ctx):
        random_image_2_5 = random.choice(jdata['image_2_5'])
        embed=discord.Embed(title="草上飛", url="https://ja.wikipedia.org/wiki/%E3%82%B0%E3%83%A9%E3%82%B9%E3%83%AF%E3%83%B3%E3%83%80%E3%83%BC", description="阿草、グラスワンダー", color=0x00ffff, timestamp= datetime.utcnow())
        embed.set_author(name="賽馬娘Pretty Derby", url=jdata['uma_wiki_url'], icon_url="https://upload.wikimedia.org/wikipedia/zh/e/ed/Umamusume_logo.png")
        embed.set_thumbnail(url=jdata['image_2_5_0'])
        embed.set_image(url=random_image_2_5)
        embed.add_field(name="CV：", value="前田玲奈", inline=True)
        embed.add_field(name="身高：", value="152cm", inline=True)
        embed.add_field(name="體重：", value="無增減", inline=True)
        embed.add_field(name="三圍：", value="B77/W53/H84", inline=True)
        embed.add_field(name="生日：", value="2月18日", inline=True)

        await ctx.send(embed=embed)
    
    @uma.command()
    async def 菱亞馬遜(self, ctx):
        random_image_2_6 = random.choice(jdata['image_2_6'])
        embed=discord.Embed(title="菱亞馬遜", url="https://ja.wikipedia.org/wiki/%E3%83%92%E3%82%B7%E3%82%A2%E3%83%9E%E3%82%BE%E3%83%B3", description="ヒシアマゾン", color=0x00ffff, timestamp= datetime.utcnow())
        embed.set_author(name="賽馬娘Pretty Derby", url=jdata['uma_wiki_url'], icon_url="https://upload.wikimedia.org/wikipedia/zh/e/ed/Umamusume_logo.png")
        embed.set_thumbnail(url=jdata['image_2_6_0'])
        embed.set_image(url=random_image_2_6)
        embed.add_field(name="CV：", value="巽悠衣子", inline=True)
        embed.add_field(name="身高：", value="160cm", inline=True)
        embed.add_field(name="體重：", value="微增（不予置評）", inline=True)
        embed.add_field(name="三圍：", value="B92/W59/H89", inline=True)
        embed.add_field(name="生日：", value="3月26日", inline=True)

        await ctx.send(embed=embed)
    
    @uma.command()
    async def 目白麥昆(self, ctx):
        random_image_3_1 = random.choice(jdata['image_3_1'])
        embed=discord.Embed(title="目白麥昆", url="https://ja.wikipedia.org/wiki/%E3%83%A1%E3%82%B8%E3%83%AD%E3%83%9E%E3%83%83%E3%82%AF%E3%82%A4%E3%83%BC%E3%83%B3", description="メジロマックイーン", color=0x00ffff, timestamp= datetime.utcnow())
        embed.set_author(name="賽馬娘Pretty Derby", url=jdata['uma_wiki_url'], icon_url="https://upload.wikimedia.org/wikipedia/zh/e/ed/Umamusume_logo.png")
        embed.set_thumbnail(url=jdata['image_3_1_0'])
        embed.set_image(url=random_image_3_1)
        embed.add_field(name="CV：", value="大西沙織", inline=True)
        embed.add_field(name="身高：", value="159cm", inline=True)
        embed.add_field(name="體重：", value="微增（目前拼命調整中！）", inline=True)
        embed.add_field(name="三圍：", value="B71/W54/H76", inline=True)
        embed.add_field(name="生日：", value="4月3日", inline=True)

        await ctx.send(embed=embed)
    
    @uma.command()
    async def 神鷹(self, ctx):
        random_image_3_2 = random.choice(jdata['image_3_2'])
        embed=discord.Embed(title="神鷹", url="https://ja.wikipedia.org/wiki/%E3%82%A8%E3%83%AB%E3%82%B3%E3%83%B3%E3%83%89%E3%83%AB%E3%83%91%E3%82%B5%E3%83%BC", description="エルコンドルパサー", color=0x00ffff, timestamp= datetime.utcnow())
        embed.set_author(name="賽馬娘Pretty Derby", url=jdata['uma_wiki_url'], icon_url="https://upload.wikimedia.org/wikipedia/zh/e/ed/Umamusume_logo.png")
        embed.set_thumbnail(url=jdata['image_3_2_0'])
        embed.set_image(url=random_image_3_2)
        embed.add_field(name="CV：", value="高橋未奈美", inline=True)
        embed.add_field(name="身高：", value="163cm", inline=True)
        embed.add_field(name="體重：", value="微增（重訓效果）", inline=True)
        embed.add_field(name="三圍：", value="B89/W58/H86", inline=True)
        embed.add_field(name="生日：", value="3月17日", inline=True)

        await ctx.send(embed=embed)
    
    @uma.command()
    async def 好歌劇(self, ctx):
        random_image_3_3 = random.choice(jdata['image_3_3'])
        embed=discord.Embed(title="好歌劇", url="https://ja.wikipedia.org/wiki/%E3%83%86%E3%82%A4%E3%82%A8%E3%83%A0%E3%82%AA%E3%83%9A%E3%83%A9%E3%82%AA%E3%83%BC", description="テイエムオペラオー", color=0x00ffff, timestamp= datetime.utcnow())
        embed.set_author(name="賽馬娘Pretty Derby", url=jdata['uma_wiki_url'], icon_url="https://upload.wikimedia.org/wikipedia/zh/e/ed/Umamusume_logo.png")
        embed.set_thumbnail(url=jdata['image_3_3_0'])
        embed.set_image(url=random_image_3_3)
        embed.add_field(name="CV：", value="德井青空", inline=True)
        embed.add_field(name="身高：", value="156cm", inline=True)
        embed.add_field(name="體重：", value="總是完美（自稱）", inline=True)
        embed.add_field(name="三圍：", value="B76/W55/H80", inline=True)
        embed.add_field(name="生日：", value="3月13日", inline=True)

        await ctx.send(embed=embed)
    
    @uma.command()
    async def 魯道夫象徵(self, ctx):
        random_image_3_4 = random.choice(jdata['image_3_4'])
        embed=discord.Embed(title="魯道夫象徵", url="https://ja.wikipedia.org/wiki/%E3%82%B7%E3%83%B3%E3%83%9C%E3%83%AA%E3%83%AB%E3%83%89%E3%83%AB%E3%83%95", description="皇帝、シンボリルドルフ", color=0x00ffff, timestamp= datetime.utcnow())
        embed.set_author(name="賽馬娘Pretty Derby", url=jdata['uma_wiki_url'], icon_url="https://upload.wikimedia.org/wikipedia/zh/e/ed/Umamusume_logo.png")
        embed.set_thumbnail(url=jdata['image_3_4_0'])
        embed.set_image(url=random_image_3_4)
        embed.add_field(name="CV：", value="田所梓", inline=True)
        embed.add_field(name="身高：", value="165cm", inline=True)
        embed.add_field(name="體重：", value="相當理想", inline=True)
        embed.add_field(name="三圍：", value="B86/W59/H85", inline=True)
        embed.add_field(name="生日：", value="3月13日", inline=True)

        await ctx.send(embed=embed)
    
    @uma.command()
    async def 氣槽(self, ctx):
        random_image_3_5 = random.choice(jdata['image_3_5'])
        embed=discord.Embed(title="氣槽", url="https://ja.wikipedia.org/wiki/%E3%82%A8%E3%82%A2%E3%82%B0%E3%83%AB%E3%83%BC%E3%83%B4", description="エアグルーヴ", color=0x00ffff, timestamp= datetime.utcnow())
        embed.set_author(name="賽馬娘Pretty Derby", url=jdata['uma_wiki_url'], icon_url="https://upload.wikimedia.org/wikipedia/zh/e/ed/Umamusume_logo.png")
        embed.set_thumbnail(url=jdata['image_3_5_0'])
        embed.set_image(url=random_image_3_5)
        embed.add_field(name="CV：", value="青木瑠璃子", inline=True)
        embed.add_field(name="身高：", value="165cm", inline=True)
        embed.add_field(name="體重：", value="調整狀態相當理想", inline=True)
        embed.add_field(name="三圍：", value="B90/W57/H86", inline=True)
        embed.add_field(name="生日：", value="4月6日", inline=True)

        await ctx.send(embed=embed)
    
    @uma.command()
    async def 愛麗數碼(self, ctx):
        random_image_3_6 = random.choice(jdata['image_3_6'])
        embed=discord.Embed(title="愛麗數碼", url="https://ja.wikipedia.org/wiki/%E3%82%A2%E3%82%B0%E3%83%8D%E3%82%B9%E3%82%BF%E3%82%AD%E3%82%AA%E3%83%B3", description="愛麗數子、アグネスタキオン", color=0x00ffff, timestamp= datetime.utcnow())
        embed.set_author(name="賽馬娘Pretty Derby", url=jdata['uma_wiki_url'], icon_url="https://upload.wikimedia.org/wikipedia/zh/e/ed/Umamusume_logo.png")
        embed.set_thumbnail(url=jdata['image_3_6_0'])
        embed.set_image(url=random_image_3_6)
        embed.add_field(name="CV：", value="上坂菫", inline=True)
        embed.add_field(name="身高：", value="143cm", inline=True)
        embed.add_field(name="體重：", value="無增減", inline=True)
        embed.add_field(name="三圍：", value="B74/W51/H75", inline=True)
        embed.add_field(name="生日：", value="5月15日", inline=True)

        await ctx.send(embed=embed)
    



    @commands.group()
    async def azur(self,ctx):
        pass
            

    @azur.command()
    async def 拉菲(self,ctx):
        random_laffey = random.choice(jdata['laffey'])
        embed=discord.Embed(title="拉菲", url=jdata['laffey_url'], description="兔兔星人、所羅門戰神、ラフィー", color=0x00ffff, timestamp= datetime.utcnow())
        embed.set_author(name="碧藍航線Azur Lane", url="https://wiki.biligame.com/blhx/%E9%A6%96%E9%A1%B5", icon_url=jdata['azur_logo'])
        embed.set_thumbnail(url=jdata['laffey_logo'])
        embed.set_image(url=random_laffey)
        embed.add_field(name="CV：", value="長繩麻理亞", inline=True)
        embed.add_field(name="類型：", value="驅逐艦", inline=True)
        embed.add_field(name="陣營：", value="白鷹", inline=True)
        embed.add_field(name="原型：", value="本森級驅逐艦7號艦", inline=True)
        embed.set_footer(text="指揮官……莫非是變態？！")
        await ctx.send(embed=embed)
    
    @azur.command()
    async def 標槍(self,ctx):
        random_Javelin = random.choice(jdata['Javelin'])
        embed=discord.Embed(title="標槍", url=jdata['Javelin_url'], description="ジャベリン", color=0x00ffff, timestamp= datetime.utcnow())
        embed.set_author(name="碧藍航線Azur Lane", url="https://wiki.biligame.com/blhx/%E9%A6%96%E9%A1%B5", icon_url=jdata['azur_logo'])
        embed.set_thumbnail(url=jdata['Javelin_logo'])
        embed.set_image(url=random_Javelin)
        embed.add_field(name="CV：", value="山根 希美", inline=True)
        embed.add_field(name="類型：", value="驅逐艦", inline=True)
        embed.add_field(name="陣營：", value="皇家", inline=True)
        #embed.add_field(name="原型：", value="本森級驅逐艦7號艦", inline=True)
        embed.set_footer(text="嘎哦——！指揮官，工口是不行的哦！")
        await ctx.send(embed=embed)

    @azur.command()
    async def 絆愛(self,ctx):
        random_Kizuna = random.choice(jdata['Kizuna'])
        embed=discord.Embed(title="", url=jdata['Kizuna_url'], description="キズナアイ", color=0x00ffff, timestamp= datetime.utcnow())
        embed.set_author(name="碧藍航線Azur Lane", url="https://wiki.biligame.com/blhx/%E9%A6%96%E9%A1%B5", icon_url=jdata['azur_logo'])
        embed.set_thumbnail(url=jdata['Kizuna_logo'])
        embed.set_image(url=random_Kizuna)
        embed.add_field(name="CV：", value="Kizuna", inline=True)
        embed.add_field(name="類型：", value="驅逐艦", inline=True)
        embed.add_field(name="陣營：", value="KizunaAI", inline=True)
        #embed.add_field(name="原型：", value="本森級驅逐艦7號艦", inline=True)
        embed.set_footer(text="很遺憾，指揮官摸到的可不是我，而是屏幕哦？")
        await ctx.send(embed=embed)

    @azur.command()
    async def 布蘭(self,ctx):
        random_Blanc = random.choice(jdata['Blanc'])
        embed=discord.Embed(title="", url=jdata['Blanc_url'], description="ブラン", color=0x00ffff, timestamp= datetime.utcnow())
        embed.set_author(name="碧藍航線Azur Lane", url="https://wiki.biligame.com/blhx/%E9%A6%96%E9%A1%B5", icon_url=jdata['azur_logo'])
        embed.set_thumbnail(url=jdata['Blanc_logo'])
        embed.set_image(url=random_Blanc)
        embed.add_field(name="CV：", value="阿澄 佳奈", inline=True)
        embed.add_field(name="類型：", value="驅逐艦", inline=True)
        embed.add_field(name="陣營：", value="海王星", inline=True)
        #embed.add_field(name="原型：", value="本森級驅逐艦7號艦", inline=True)
        embed.set_footer(text="你在期待什麼？")
        await ctx.send(embed=embed)

    @azur.command()
    async def 莫里森(self,ctx):
        random_Morrison = random.choice(jdata['Morrison'])
        embed=discord.Embed(title="莫里森", url=jdata['Morrison_url'], description="モリソン", color=0x00ffff, timestamp= datetime.utcnow())
        embed.set_author(name="碧藍航線Azur Lane", url="https://wiki.biligame.com/blhx/%E9%A6%96%E9%A1%B5", icon_url=jdata['azur_logo'])
        embed.set_thumbnail(url=jdata['Morrison_logo'])
        embed.set_image(url=random_Morrison)
        embed.add_field(name="CV：", value="並木櫻", inline=True)
        embed.add_field(name="類型：", value="驅逐艦", inline=True)
        embed.add_field(name="陣營：", value="白鷹", inline=True)
        #embed.add_field(name="原型：", value="本森級驅逐艦7號艦", inline=True)
        embed.set_footer(text="呀，小熊它暴走了！")
        await ctx.send(embed=embed)

    @azur.command()
    async def 西南風(self,ctx):
        random_Libeccio = random.choice(jdata['Libeccio'])
        embed=discord.Embed(title="西南風", url=jdata['Libeccio_url'], description="リベッチオ", color=0x00ffff, timestamp= datetime.utcnow())
        embed.set_author(name="碧藍航線Azur Lane", url="https://wiki.biligame.com/blhx/%E9%A6%96%E9%A1%B5", icon_url=jdata['azur_logo'])
        embed.set_thumbnail(url=jdata['Libeccio_logo'])
        embed.set_image(url=random_Libeccio)
        embed.add_field(name="CV：", value="永野愛理", inline=True)
        embed.add_field(name="類型：", value="驅逐艦", inline=True)
        embed.add_field(name="陣營：", value="撒丁帝國", inline=True)
        #embed.add_field(name="原型：", value="本森級驅逐艦7號艦", inline=True)
        embed.set_footer(text="平平的是吧？和西北風姐姐一樣哦！")
        await ctx.send(embed=embed)

    @azur.command()
    async def 西北風 (self,ctx):
        random_Maestrale = random.choice(jdata['Maestrale'])
        embed=discord.Embed(title="西北風 ", url=jdata['Maestrale_url'], description="マエストラーレ", color=0x00ffff, timestamp= datetime.utcnow())
        embed.set_author(name="碧藍航線Azur Lane", url="https://wiki.biligame.com/blhx/%E9%A6%96%E9%A1%B5", icon_url=jdata['azur_logo'])
        embed.set_thumbnail(url=jdata['Maestrale_logo'])
        embed.set_image(url=random_Maestrale)
        embed.add_field(name="CV：", value="永野愛理", inline=True)
        embed.add_field(name="類型：", value="驅逐艦", inline=True)
        embed.add_field(name="陣營：", value="撒丁帝國", inline=True)
        #embed.add_field(name="原型：", value="本森級驅逐艦7號艦", inline=True)
        embed.set_footer(text="……做，做什麼！？")
        await ctx.send(embed=embed)

    @azur.command()
    async def 雷鳴(self,ctx):
        random_Gremyashchy = random.choice(jdata['Gremyashchy'])
        embed=discord.Embed(title="雷鳴", url=jdata['Gremyashchy_url'], description="グレミャーシュチ", color=0x00ffff, timestamp= datetime.utcnow())
        embed.set_author(name="碧藍航線Azur Lane", url="https://wiki.biligame.com/blhx/%E9%A6%96%E9%A1%B5", icon_url=jdata['azur_logo'])
        embed.set_thumbnail(url=jdata['Gremyashchy_logo'])
        embed.set_image(url=random_Gremyashchy)
        embed.add_field(name="CV：", value="山田麻莉奈", inline=True)
        embed.add_field(name="類型：", value="驅逐艦", inline=True)
        embed.add_field(name="陣營：", value="北方聯合", inline=True)
        #embed.add_field(name="原型：", value="本森級驅逐艦7號艦", inline=True)
        embed.set_footer(text="指揮官…果然是變態？")
        await ctx.send(embed=embed)

    @azur.command()
    async def Z28(self,ctx):
        random_Z28 = random.choice(jdata['Z28'])
        embed=discord.Embed(title="Z28", url=jdata['Z28_url'], description="Z28", color=0x00ffff, timestamp= datetime.utcnow())
        embed.set_author(name="碧藍航線Azur Lane", url="https://wiki.biligame.com/blhx/%E9%A6%96%E9%A1%B5", icon_url=jdata['azur_logo'])
        embed.set_thumbnail(url=jdata['Z28_logo'])
        embed.set_image(url=random_Z28)
        embed.add_field(name="CV：", value="木村千咲", inline=True)
        embed.add_field(name="類型：", value="驅逐艦", inline=True)
        embed.add_field(name="陣營：", value="鐵血", inline=True)
        #embed.add_field(name="原型：", value="本森級驅逐艦7號艦", inline=True)
        embed.set_footer(text="做這樣的事可是會被女孩子討厭的哦？")
        await ctx.send(embed=embed)

    @azur.command()
    async def Z24(self,ctx):
        random_Z24 = random.choice(jdata['Z24'])
        embed=discord.Embed(title="Z24", url=jdata['Z24_url'], description="Z24", color=0x00ffff, timestamp= datetime.utcnow())
        embed.set_author(name="碧藍航線Azur Lane", url="https://wiki.biligame.com/blhx/%E9%A6%96%E9%A1%B5", icon_url=jdata['azur_logo'])
        embed.set_thumbnail(url=jdata['Z24_logo'])
        embed.set_image(url=random_Z24)
        embed.add_field(name="CV：", value="首藤志奈", inline=True)
        embed.add_field(name="類型：", value="驅逐艦", inline=True)
        embed.add_field(name="陣營：", value="鐵血", inline=True)
        #embed.add_field(name="原型：", value="本森級驅逐艦7號艦", inline=True)
        embed.set_footer(text="敢對吾如此不敬…想必已經做好足夠的心理準備了吧，凡人…？")
        await ctx.send(embed=embed)

    @azur.command()
    async def Z26(self,ctx):
        random_Z26 = random.choice(jdata['Z26'])
        embed=discord.Embed(title="Z26", url=jdata['Z26_url'], description="Z26", color=0x00ffff, timestamp= datetime.utcnow())
        embed.set_author(name="碧藍航線Azur Lane", url="https://wiki.biligame.com/blhx/%E9%A6%96%E9%A1%B5", icon_url=jdata['azur_logo'])
        embed.set_thumbnail(url=jdata['Z26_logo'])
        embed.set_image(url=random_Z26)
        embed.add_field(name="CV：", value="天野聰美", inline=True)
        embed.add_field(name="類型：", value="驅逐艦", inline=True)
        embed.add_field(name="陣營：", value="鐵血", inline=True)
        #embed.add_field(name="原型：", value="本森級驅逐艦7號艦", inline=True)
        embed.set_footer(text="不純潔的接觸，不行！")
        await ctx.send(embed=embed)

    @azur.command()
    async def 伊卡洛斯(self,ctx):
        random_Icarus = random.choice(jdata['Icarus'])
        embed=discord.Embed(title="伊卡洛斯", url=jdata['Icarus_url'], description="イカルス", color=0x00ffff, timestamp= datetime.utcnow())
        embed.set_author(name="碧藍航線Azur Lane", url="https://wiki.biligame.com/blhx/%E9%A6%96%E9%A1%B5", icon_url=jdata['azur_logo'])
        embed.set_thumbnail(url=jdata['Icarus_logo'])
        embed.set_image(url=random_Icarus)
        embed.add_field(name="CV：", value="", inline=True)
        embed.add_field(name="類型：", value="驅逐艦", inline=True)
        embed.add_field(name="陣營：", value="皇家", inline=True)
        #embed.add_field(name="原型：", value="本森級驅逐艦7號艦", inline=True)
        embed.set_footer(text="這、這種事情果然還是…（///")
        await ctx.send(embed=embed)

    @azur.command()
    async def 塔爾圖(self,ctx):
        random_Tartu = random.choice(jdata['Tartu'])
        embed=discord.Embed(title="塔爾圖", url=jdata['Tartu_url'], description="タルテュ", color=0x00ffff, timestamp= datetime.utcnow())
        embed.set_author(name="碧藍航線Azur Lane", url="https://wiki.biligame.com/blhx/%E9%A6%96%E9%A1%B5", icon_url=jdata['azur_logo'])
        embed.set_thumbnail(url=jdata['Tartu_logo'])
        embed.set_image(url=random_Tartu)
        embed.add_field(name="CV：", value="幸村惠理", inline=True)
        embed.add_field(name="類型：", value="驅逐艦", inline=True)
        embed.add_field(name="陣營：", value="維希教廷", inline=True)
        #embed.add_field(name="原型：", value="本森級驅逐艦7號艦", inline=True)
        embed.set_footer(text="唔…按照沃克蘭推薦的書來說…這種時候應該是…證據確鑿，人贓俱獲…吧？")
        await ctx.send(embed=embed)

    @azur.command()
    async def 長波(self,ctx):
        random_Naganami = random.choice(jdata['Naganami'])
        embed=discord.Embed(title="長波", url=jdata['Naganami_url'], description="萇", color=0x00ffff, timestamp= datetime.utcnow())
        embed.set_author(name="碧藍航線Azur Lane", url="https://wiki.biligame.com/blhx/%E9%A6%96%E9%A1%B5", icon_url=jdata['azur_logo'])
        embed.set_thumbnail(url=jdata['Naganami_logo'])
        embed.set_image(url=random_Naganami)
        embed.add_field(name="CV：", value="明日葉", inline=True)
        embed.add_field(name="類型：", value="驅逐艦", inline=True)
        embed.add_field(name="陣營：", value="重櫻", inline=True)
        #embed.add_field(name="原型：", value="本森級驅逐艦7號艦", inline=True)
        embed.set_footer(text="指揮官，現在姑且還是工作時間哦......")
        await ctx.send(embed=embed)

    @azur.command()
    async def 明斯克(self,ctx):
        random_Minsk = random.choice(jdata['Minsk'])
        embed=discord.Embed(title="明斯克", url=jdata['Minsk_url'], description="ミンスク", color=0x00ffff, timestamp= datetime.utcnow())
        embed.set_author(name="碧藍航線Azur Lane", url="https://wiki.biligame.com/blhx/%E9%A6%96%E9%A1%B5", icon_url=jdata['azur_logo'])
        embed.set_thumbnail(url=jdata['Minsk_logo'])
        embed.set_image(url=random_Minsk)
        embed.add_field(name="CV：", value="原優子", inline=True)
        embed.add_field(name="類型：", value="驅逐艦", inline=True)
        embed.add_field(name="陣營：", value="北方聯合", inline=True)
        #embed.add_field(name="原型：", value="本森級驅逐艦7號艦", inline=True)
        embed.set_footer(text="！？…這該不會是對我之前行為的報復吧？！")
        await ctx.send(embed=embed)

    @azur.command()
    async def 威嚴(self,ctx):
        random_Grozny = random.choice(jdata['Grozny'])
        embed=discord.Embed(title="威嚴", url=jdata['Grozny_url'], description="グロズヌイ", color=0x00ffff, timestamp= datetime.utcnow())
        embed.set_author(name="碧藍航線Azur Lane", url="https://wiki.biligame.com/blhx/%E9%A6%96%E9%A1%B5", icon_url=jdata['azur_logo'])
        embed.set_thumbnail(url=jdata['Grozny_logo'])
        embed.set_image(url=random_Grozny)
        embed.add_field(name="CV：", value="都丸ちよ", inline=True)
        embed.add_field(name="類型：", value="驅逐艦", inline=True)
        embed.add_field(name="陣營：", value="北方聯合", inline=True)
        #embed.add_field(name="原型：", value="本森級驅逐艦7號艦", inline=True)
        embed.set_footer(text="кролик生氣了也會咬人的。…嗯？這孩子的話，應該是砍人…才對？")
        await ctx.send(embed=embed)

    @azur.command()
    async def 龍騎兵(self,ctx):
        random_Carabiniere = random.choice(jdata['Carabiniere'])
        embed=discord.Embed(title="龍騎兵", url=jdata['Carabiniere_url'], description="カラビニエーレ", color=0x00ffff, timestamp= datetime.utcnow())
        embed.set_author(name="碧藍航線Azur Lane", url="https://wiki.biligame.com/blhx/%E9%A6%96%E9%A1%B5", icon_url=jdata['azur_logo'])
        embed.set_thumbnail(url=jdata['Carabiniere_logo'])
        embed.set_image(url=random_Carabiniere)
        embed.add_field(name="CV：", value="立花理香", inline=True)
        embed.add_field(name="類型：", value="驅逐艦", inline=True)
        embed.add_field(name="陣營：", value="撒丁帝國", inline=True)
        #embed.add_field(name="原型：", value="本森級驅逐艦7號艦", inline=True)
        embed.set_footer(text="請，請不要為難屬下！")
        await ctx.send(embed=embed)

    @azur.command()
    async def 倔強(self,ctx):
        random_LOpiniatre = random.choice(jdata['LOpiniatre'])
        embed=discord.Embed(title="倔強", url=jdata['LOpiniatre_url'], description="ルピニャート", color=0x00ffff, timestamp= datetime.utcnow())
        embed.set_author(name="碧藍航線Azur Lane", url="https://wiki.biligame.com/blhx/%E9%A6%96%E9%A1%B5", icon_url=jdata['azur_logo'])
        embed.set_thumbnail(url=jdata['LOpiniatre_logo'])
        embed.set_image(url=random_LOpiniatre)
        embed.add_field(name="CV：", value="後藤麻衣", inline=True)
        embed.add_field(name="類型：", value="驅逐艦", inline=True)
        embed.add_field(name="陣營：", value="自由鳶尾", inline=True)
        #embed.add_field(name="原型：", value="本森級驅逐艦7號艦", inline=True)
        embed.set_footer(text="稍等一下，我找找能把人變成兔子的咒語。")
        await ctx.send(embed=embed)

    @azur.command()
    async def Z2(self,ctx):
        random_Thiele = random.choice(jdata['Thiele'])
        embed=discord.Embed(title="Z2", url=jdata['Thiele_url'], description="ゲオルク・ティーレ", color=0x00ffff, timestamp= datetime.utcnow())
        embed.set_author(name="碧藍航線Azur Lane", url="https://wiki.biligame.com/blhx/%E9%A6%96%E9%A1%B5", icon_url=jdata['azur_logo'])
        embed.set_thumbnail(url=jdata['Thiele_logo'])
        embed.set_image(url=random_Thiele)
        embed.add_field(name="CV：", value="河瀨茉希", inline=True)
        embed.add_field(name="類型：", value="驅逐艦", inline=True)
        embed.add_field(name="陣營：", value="鐵血", inline=True)
        #embed.add_field(name="原型：", value="本森級驅逐艦7號艦", inline=True)
        embed.set_footer(text="指揮官，在表現勇氣的方式裡，我認為這是最差的一種")
        await ctx.send(embed=embed)

    @azur.command()
    async def 巻波(self,ctx):
        random_Makinami = random.choice(jdata['Makinami'])
        embed=discord.Embed(title="巻波", url=jdata['Makinami_url'], description="巻波", color=0x00ffff, timestamp= datetime.utcnow())
        embed.set_author(name="碧藍航線Azur Lane", url="https://wiki.biligame.com/blhx/%E9%A6%96%E9%A1%B5", icon_url=jdata['azur_logo'])
        embed.set_thumbnail(url=jdata['Makinami_logo'])
        embed.set_image(url=random_Makinami)
        embed.add_field(name="CV：", value="田辺留依", inline=True)
        embed.add_field(name="類型：", value="驅逐艦", inline=True)
        embed.add_field(name="陣營：", value="重櫻", inline=True)
        #embed.add_field(name="原型：", value="本森級驅逐艦7號艦", inline=True)
        embed.set_footer(text="指揮官，為什麼突然緊緊抱住我！？")
        await ctx.send(embed=embed)

    @azur.command()
    async def 馬拉尼(self,ctx):
        random_Mullany = random.choice(jdata['Mullany'])
        embed=discord.Embed(title="馬拉尼", url=jdata['Mullany_url'], description="マラニー", color=0x00ffff, timestamp= datetime.utcnow())
        embed.set_author(name="碧藍航線Azur Lane", url="https://wiki.biligame.com/blhx/%E9%A6%96%E9%A1%B5", icon_url=jdata['azur_logo'])
        embed.set_thumbnail(url=jdata['Mullany_logo'])
        embed.set_image(url=random_Mullany)
        embed.add_field(name="CV：", value="大龜明日香", inline=True)
        embed.add_field(name="類型：", value="驅逐艦", inline=True)
        embed.add_field(name="陣營：", value="白鷹", inline=True)
        #embed.add_field(name="原型：", value="本森級驅逐艦7號艦", inline=True)
        embed.set_footer(text="指、指揮官果然也是對色色的東西感興趣的呢……")
        await ctx.send(embed=embed)

    @azur.command()
    async def Z35(self,ctx):
        random_Z35 = random.choice(jdata['Z35'])
        embed=discord.Embed(title="Z35", url=jdata['Z35_url'], description="Z35", color=0x00ffff, timestamp= datetime.utcnow())
        embed.set_author(name="碧藍航線Azur Lane", url="https://wiki.biligame.com/blhx/%E9%A6%96%E9%A1%B5", icon_url=jdata['azur_logo'])
        embed.set_thumbnail(url=jdata['Z35_logo'])
        embed.set_image(url=random_Z35)
        embed.add_field(name="CV：", value="大橋彩香", inline=True)
        embed.add_field(name="類型：", value="驅逐艦", inline=True)
        embed.add_field(name="陣營：", value="鐵血", inline=True)
        #embed.add_field(name="原型：", value="本森級驅逐艦7號艦", inline=True)
        embed.set_footer(text="指揮官，雖然我的表情沒有變化，實際上好感度已經下降了哦")
        await ctx.send(embed=embed)

    @azur.command()
    async def 無敵(self,ctx):
        random_Matchless = random.choice(jdata['Matchless'])
        embed=discord.Embed(title="無敵", url=jdata['Matchless_url'], description="マッチレス", color=0x00ffff, timestamp= datetime.utcnow())
        embed.set_author(name="碧藍航線Azur Lane", url="https://wiki.biligame.com/blhx/%E9%A6%96%E9%A1%B5", icon_url=jdata['azur_logo'])
        embed.set_thumbnail(url=jdata['Matchless_logo'])
        embed.set_image(url=random_Matchless)
        embed.add_field(name="CV：", value="花守由美里", inline=True)
        embed.add_field(name="類型：", value="驅逐艦", inline=True)
        embed.add_field(name="陣營：", value="皇家", inline=True)
        #embed.add_field(name="原型：", value="本森級驅逐艦7號艦", inline=True)
        embed.set_footer(text="我對指揮官的評價，稍稍降低囉。")
        await ctx.send(embed=embed)

    @azur.command()
    async def 宵月(self,ctx):
        random_Yoizuki = random.choice(jdata['Yoizuki'])
        embed=discord.Embed(title="宵月", url=jdata['Yoizuki_url'], description="楛", color=0x00ffff, timestamp= datetime.utcnow())
        embed.set_author(name="碧藍航線Azur Lane", url="https://wiki.biligame.com/blhx/%E9%A6%96%E9%A1%B5", icon_url=jdata['azur_logo'])
        embed.set_thumbnail(url=jdata['Yoizuki_logo'])
        embed.set_image(url=random_Yoizuki)
        embed.add_field(name="CV：", value="持月玲依", inline=True)
        embed.add_field(name="類型：", value="驅逐艦", inline=True)
        embed.add_field(name="陣營：", value="重櫻", inline=True)
        #embed.add_field(name="原型：", value="本森級驅逐艦7號艦", inline=True)
        embed.set_footer(text="指揮官，你想被大卸八塊嗎？")
        await ctx.send(embed=embed)

    @azur.command()
    async def 春月(self,ctx):
        random_Harutsuki = random.choice(jdata['Harutsuki'])
        embed=discord.Embed(title="春月", url=jdata['Harutsuki_url'], description="", color=0x00ffff, timestamp= datetime.utcnow())
        embed.set_author(name="碧藍航線Azur Lane", url="https://wiki.biligame.com/blhx/%E9%A6%96%E9%A1%B5", icon_url=jdata['azur_logo'])
        embed.set_thumbnail(url=jdata['Harutsuki_logo'])
        embed.set_image(url=random_Harutsuki)
        embed.add_field(name="CV：", value="持月玲依", inline=True)
        embed.add_field(name="類型：", value="驅逐艦", inline=True)
        embed.add_field(name="陣營：", value="重櫻", inline=True)
        #embed.add_field(name="原型：", value="本森級驅逐艦7號艦", inline=True)
        embed.set_footer(text="殿，殿下！請，請不要這樣！嗚嗚……")
        await ctx.send(embed=embed)

    @azur.command()
    async def 太原(self,ctx):
        random_Yuan = random.choice(jdata['Yuan'])
        embed=discord.Embed(title="太原", url=jdata['Yuan_url'], description="太原", color=0x00ffff, timestamp= datetime.utcnow())
        embed.set_author(name="碧藍航線Azur Lane", url="https://wiki.biligame.com/blhx/%E9%A6%96%E9%A1%B5", icon_url=jdata['azur_logo'])
        embed.set_thumbnail(url=jdata['Yuan_logo'])
        embed.set_image(url=random_Yuan)
        embed.add_field(name="CV：", value="水橋香織", inline=True)
        embed.add_field(name="類型：", value="驅逐艦", inline=True)
        embed.add_field(name="陣營：", value="東煌", inline=True)
        #embed.add_field(name="原型：", value="本森級驅逐艦7號艦", inline=True)
        embed.set_footer(text="哇、哇，指、指揮官，請不要這樣……")
        await ctx.send(embed=embed)

    @azur.command()
    async def 長春(self,ctx):
        random_Chang_Chun = random.choice(jdata['Chang_Chun'])
        embed=discord.Embed(title="長春", url=jdata['Chang_Chun_url'], description="長春", color=0x00ffff, timestamp= datetime.utcnow())
        embed.set_author(name="碧藍航線Azur Lane", url="https://wiki.biligame.com/blhx/%E9%A6%96%E9%A1%B5", icon_url=jdata['azur_logo'])
        embed.set_thumbnail(url=jdata['Chang_Chun_logo'])
        embed.set_image(url=random_Chang_Chun)
        embed.add_field(name="CV：", value="水橋香織", inline=True)
        embed.add_field(name="類型：", value="驅逐艦", inline=True)
        embed.add_field(name="陣營：", value="東煌", inline=True)
        #embed.add_field(name="原型：", value="本森級驅逐艦7號艦", inline=True)
        embed.set_footer(text="指揮官，是這樣的人嗎？")
        await ctx.send(embed=embed)

    @azur.command()
    async def 鞍山(self,ctx):
        random_An_Shan = random.choice(jdata['An_Shan'])
        embed=discord.Embed(title="鞍山", url=jdata['An_Shan_url'], description="鞍山", color=0x00ffff, timestamp= datetime.utcnow())
        embed.set_author(name="碧藍航線Azur Lane", url="https://wiki.biligame.com/blhx/%E9%A6%96%E9%A1%B5", icon_url=jdata['azur_logo'])
        embed.set_thumbnail(url=jdata['An_Shan_logo'])
        embed.set_image(url=random_An_Shan)
        embed.add_field(name="CV：", value="阿澄佳奈", inline=True)
        embed.add_field(name="類型：", value="驅逐艦", inline=True)
        embed.add_field(name="陣營：", value="東煌", inline=True)
        #embed.add_field(name="原型：", value="本森級驅逐艦7號艦", inline=True)
        embed.set_footer(text="餵——妹妹們可能會看到啊")
        await ctx.send(embed=embed)

    @azur.command()
    async def 勇敢(self,ctx):
        random_Hardy = random.choice(jdata['Hardy'])
        embed=discord.Embed(title="勇敢", url=jdata['Hardy_url'], description="ハーディ", color=0x00ffff, timestamp= datetime.utcnow())
        embed.set_author(name="碧藍航線Azur Lane", url="https://wiki.biligame.com/blhx/%E9%A6%96%E9%A1%B5", icon_url=jdata['azur_logo'])
        embed.set_thumbnail(url=jdata['Hardy_logo'])
        embed.set_image(url=random_Hardy)
        embed.add_field(name="CV：", value="七瀨彩夏", inline=True)
        embed.add_field(name="類型：", value="驅逐艦", inline=True)
        embed.add_field(name="陣營：", value="皇家", inline=True)
        #embed.add_field(name="原型：", value="本森級驅逐艦7號艦", inline=True)
        embed.set_footer(text="刺劍雖是裝飾，戳到了也是很疼的！")
        await ctx.send(embed=embed)

    @azur.command()
    async def 螢火蟲(self,ctx):
        random_Glowworm = random.choice(jdata['Glowworm'])
        embed=discord.Embed(title="螢火蟲", url=jdata['Glowworm_url'], description="グローウォーム", color=0x00ffff, timestamp= datetime.utcnow())
        embed.set_author(name="碧藍航線Azur Lane", url="https://wiki.biligame.com/blhx/%E9%A6%96%E9%A1%B5", icon_url=jdata['azur_logo'])
        embed.set_thumbnail(url=jdata['Glowworm_logo'])
        embed.set_image(url=random_Glowworm)
        embed.add_field(name="CV：", value="五十嵐裕美", inline=True)
        embed.add_field(name="類型：", value="驅逐艦", inline=True)
        embed.add_field(name="陣營：", value="皇家", inline=True)
        #embed.add_field(name="原型：", value="本森級驅逐艦7號艦", inline=True)
        embed.set_footer(text="唔姆姆！！！hentai指揮官！吃我頭槌！")
        await ctx.send(embed=embed)

    @azur.command()
    async def 吸血鬼(self,ctx):
        random_Vampire = random.choice(jdata['Vampire'])
        embed=discord.Embed(title="吸血鬼", url=jdata['Vampire_url'], description="ヴァンパイア", color=0x00ffff, timestamp= datetime.utcnow())
        embed.set_author(name="碧藍航線Azur Lane", url="https://wiki.biligame.com/blhx/%E9%A6%96%E9%A1%B5", icon_url=jdata['azur_logo'])
        embed.set_thumbnail(url=jdata['Vampire_logo'])
        embed.set_thumbnail(url="https://patchwiki.biligame.com/images/blhx/2/23/017oj1raye9e7nahesf9oqsexk5yxfm.mp3")
        embed.set_image(url=random_Vampire)
        embed.add_field(name="CV：", value="釘宮理惠", inline=True)
        embed.add_field(name="類型：", value="驅逐艦", inline=True)
        embed.add_field(name="陣營：", value="皇家", inline=True)
        #embed.add_field(name="原型：", value="本森級驅逐艦7號艦", inline=True)
        embed.set_footer(text="誒！笨蛋！色狼！蘿莉控！")
        await ctx.send(embed=embed)
        await ctx.send("https://patchwiki.biligame.com/images/blhx/2/23/017oj1raye9e7nahesf9oqsexk5yxfm.mp3")

    # @azur.command()
    # async def (self,ctx):
    #     random_ = random.choice(jdata[''])
    #     embed=discord.Embed(title="", url=jdata['_url'], description="", color=0x00ffff, timestamp= datetime.utcnow())
    #     embed.set_author(name="碧藍航線Azur Lane", url="https://wiki.biligame.com/blhx/%E9%A6%96%E9%A1%B5", icon_url=jdata['azur_logo'])
    #     embed.set_thumbnail(url=jdata['_logo'])
    #     embed.set_image(url=random_)
    #     embed.add_field(name="CV：", value="", inline=True)
    #     embed.add_field(name="類型：", value="驅逐艦", inline=True)
    #     embed.add_field(name="陣營：", value="", inline=True)
    #     #embed.add_field(name="原型：", value="本森級驅逐艦7號艦", inline=True)
    #     embed.set_footer(text="")
    #     await ctx.send(embed=embed)





def setup(bot):   #傳回去bot.py裡面的bot
    bot.add_cog(Gamming(bot))